changing image name

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,13 +1,14 @@
-name: Check docker image
+name: Auto build images when upstream is updated or not
 
 on:
   push:
-    branches:
+    branches: 
       - auto-update
-
 jobs:
-  docker:
+  check:
     runs-on: ubuntu-latest
+    outputs:
+      needs-updating: ${{ steps.check.outputs.needs-updating }}
     steps:
       - name: Checkout
         uses: actions/checkout@v3
@@ -16,65 +17,58 @@ jobs:
         id: check
         uses: clowa/docker-image-update-checker@342608bb9829d85eeeeb292e78115184b5a6657d
         with:
-          base-image: nginx:1.21.0
-          image: user/app:latest
+          base-image: ubuntu:22.04
+          image: testing-branch/auto-update:latest
           platforms: linux/arm/v6,linux/arm/v7,linux/arm64
         env:
           DEBUG: true
+         
 
-      - name: Build and push
-        uses: docker/build-push-action@v3
-        with:
-          context: .
-          push: true
-          tags: user/app:latest
-        if: steps.check.outputs.needs-updating == 'true'
+  build: 
+    needs: check
+    runs-on: ubuntu-latest
+    permissions: 
+      contents: read
+      packages: write
 
-  # build: 
-  #   needs: check
-  #   runs-on: ubuntu-latest
-  #   permissions: 
-  #     contents: read
-  #     packages: write
-
-  #   if: needs.check.outputs.needs-updating == 'true'
-  #   steps:
-  #     - name: Checkout repositry
-  #       uses: actions/checkout@v3
+    if: needs.check.outputs.needs-updating == 'true'
+    steps:
+      - name: Checkout repositry
+        uses: actions/checkout@v3
  
-  #     - name: pull updated base image
-  #       run: | 
-  #           docker pull ubuntu:22.04
+      - name: pull updated base image
+        run: | 
+            docker pull ubuntu:22.04
       
-  #     - name: Log in to the Container registry
-  #       uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
-  #       with: 
-  #           registry: ghcr.io
-  #           username: ${{ github.actor }}
-  #           password: ${{ secrets.GITHUB_TOKEN }}
+      - name: Log in to the Container registry
+        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
+        with: 
+            registry: ghcr.io
+            username: ${{ github.actor }}
+            password: ${{ secrets.GITHUB_TOKEN }}
 
-  #     - name: Reuild the Docker image
-  #       run: |
-  #          testing-branch/
-  #          [[ "$GITHUB_REF_NAME" == "master" ]] && export TAG="latest" || TAG="$GITHUB_REF_NAME"
-  #          docker build . --tag ghcr.io/getfundwave/fundwave:$TAG
+      - name: Reuild the Docker image
+        run: |
+           testing-branch/
+           [[ "$GITHUB_REF_NAME" == "master" ]] && export TAG="latest" || TAG="$GITHUB_REF_NAME"
+           docker build . --tag ghcr.io/getfundwave/fundwave:$TAG
 
-  #     - name: Check if container is working with rebuild image
-  #       run: | 
-  #           containerId=$(docker run --rm -it -d ghcr.io/getfundwave/fundwave:$TAG)
-  #           sleep 60
-  #           containerRunning=$(docker inspect --format="{{ .State.Running }}" $containerId 2> /dev/null)
-  #           if [ "$containerRunning" == "true" ]; then
-  #             echo "container is working with rebuild image"
-  #           else 
-  #             echo "there is an error in updated base image"
-  #             exit 1
-  #           fi
+      - name: Check if container is working with rebuild image
+        run: | 
+            containerId=$(docker run --rm -it -d ghcr.io/getfundwave/fundwave:$TAG)
+            sleep 60
+            containerRunning=$(docker inspect --format="{{ .State.Running }}" $containerId 2> /dev/null)
+            if [ "$containerRunning" == "true" ]; then
+              echo "container is working with rebuild image"
+            else 
+              echo "there is an error in updated base image"
+              exit 1
+            fi
 
-  #     - name: Publish new docker image
-  #       env:
-  #         TOKEN: ${{secrets.GITHUB_TOKEN}}
-  #       run: |
-  #         echo  $TOKEN | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
-  #         [[ "$GITHUB_REF_NAME" == "master" ]] && export TAG="latest" || TAG="$GITHUB_REF_NAME"
-  #         docker push ghcr.io/getfundwave/fundwave:$TAG
+      - name: Publish new docker image
+        env:
+          TOKEN: ${{secrets.GITHUB_TOKEN}}
+        run: |
+          echo  $TOKEN | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
+          [[ "$GITHUB_REF_NAME" == "master" ]] && export TAG="latest" || TAG="$GITHUB_REF_NAME"
+          docker push ghcr.io/getfundwave/fundwave:$TAG
